version: '3.7'
services:
  roulette-api:
    container_name: roulette-api-container
    ports:
      - 9090:9090
    expose:
      - 9090
    build: .
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    hostname: redis