server:
  port: 9090
  servlet:
    context-path: /roulette
logging:
  level:
    org.springframework: DEBUG
spring:
  redis:
    host: redis
    port: 6379
    max-total: 8
    max-idle: 8
    min-idle: 8
    min-evictable-idle: 1800000
roulette:
  limits:
    max: 36
    min: 0